name: Build Finger Drag

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          target: Android64
          sdk: given

      - uses: actions/upload-artifact@v4
        with:
          name: Finger-Drag-Android64
          path: ${{ steps.build.outputs.build-output }}/*.geode
